- .devcontainer/Dockerfile
- requirements.txt
According to the [documentation](https://isciences.github.io/exactextract/installation.html) of exactetract, 
- added to install gcc, cmake and libgeos-dev in Dockerfile.
- also added `exactextract` in requirements.txt
> fix: add exactextract and required packages to Docker

- cbsurge/admin/__init__.py
- cbsurge/admin/ocha.py
- cbsurge/cli.py
This PR improves the way bbox and admin/osm levels args are handled. bbox is now of type float and requires 4 values separated by space
closes #80
> improved arg parsing

- cbsurge/admin/__init__.py
fixes #79
result can be saved as the following commands
```
python -m  cbsurge.cli admin osm -b "27.767944,-5.063586,31.734009,-0.417477" -l 0 > osm.geojson
python -m  cbsurge.cli admin ocha -b "27.767944,-5.063586,31.734009,-0.417477" -l 0 > ocha.geojson
```
or it can be piped to ogr or tippecanoe (any commands)
> fix: export geojson result to sdtout to allow to reuse data for other commands or save a file

- .devcontainer/Dockerfile
- Dockerfile
- README.md
- cbsurge/cli.py
- cbsurge/session.py
- pyproject.toml
closes #95
@iferencik 
I likely don't have appropriate role to access to storage account while I only have `reader` and `contributor` roles. You looks having different role (`Storage Blob Data Contributor`) from mine. Could you try this branch to check if you can access blob?
```shell
make build # to build docker image
make shell # to enter container
az login # authenticate with Azure CLI
pipenv run rapida init # init command to authenticate
pipenv run python -m cbsurge.session # run my test script to download a catalog.json
```
<details>
<summary>permission error logs</summary>
```shell
root@cda20016d7fc:/workspace# pipenv run python -m cbsurge.session
INFO:azure.identity._credentials.environment:No environment configuration found. …
```
> feat: add Session class and rapida init command to authenticate

- .github/workflows/ci.yml
- Dockerfile
- README.md
- create_user.sh
fixes #102 
it is not installing globally, but use `PIPENV_VENV_IN_PROJECT=1` variable to install venv under `/app` folder, so all users can share same environment.
I added a command in bashrc to automatically move to `/app` to run `pipenv shell`, so basically `rapida` command is available anywhere unless users exit
> share venv with other users

- .azure/aci-deploy.yaml
- Dockerfile
- docker-compose.yaml
- entrypoint.sh
- jupyterhub_config.py
- pyproject.toml
launch JupyterHub in docker container
- allowed system users to login to JupyterHub
- launch the server as port 8000 in local, and launch it as port 443 in production (if `PRODUCTION=true` variable is registered)
> add jupyterhub to docker

- .gitignore
- cbsurge/stats/GDALRasterSource.py
- cbsurge/stats/OGRDataSource.py
- cbsurge/stats/ZonalStats.py
- cbsurge/stats/__init__.py
- tests/cbsurge/stats/test_ZonalStats.py
Instead of passing target_srid as a integer, It is better to use target_srs as an argument to give user the freedom to use whichever they want
> fix: change target_srs argument to target_crs

- Dockerfile
- pyproject.toml
rapida command does not work because of missing dependencies
> fix: add missing dependencies to pyproject.toml

- cbsurge/cli.py
previously I fixed cli.py to delete duplication of codes, however @iferencik reverted changes by PR https://github.com/UNDP-Data/geo-cb-surge/pull/107
> fix: delete duplicated codes from cli.py

- cbsurge/exposure/population/__init__.py
- cbsurge/exposure/population/worldpop.py
- tests/cbsurge/test_cli.py
The following PR implements download from azure function and implements the CLI to download both aggregate and non-aggregate files from azure storage.
Usage:
` rapida population download --country BHS --download-path data/BHS/cogs --non-aggregates`
this will download all the non-aggregate files to the data/BHS/cogs folder.
` rapida population download --country BHS --download-path data/BHS/cogs/male --sex male --non-aggregates`
this will download all the non-aggregate files that are within the `male` folder for the country `BHS` to data/BHS/cogs/male folder
> feat: implement download from azure

- cbsurge/session.py
fixes #121
create containerClient directly instead of using getServiceClient method, so session will be automatically closed correctly.
also, add `__aenter__` and `__aexit__` to the class, so it can support `async with Session() as session` now.
> fix: fixed get_blob_container_client to get container client directly

- cbsurge/exposure/population/pop_coefficient.py
- tests/cbsurge/exposure/population/test_pop_coefficient.py
fixes #146 
added the below function to compute coefficient.
```python
def get_pop_coefficient_world_bank(target_year: int, country_code: str) -> list[int | float]:
"""
Fetches population data from the World Bank API and calculates the population growth coefficient.
Parameters:
target_year (int): The base year for comparison.
country_code (str): The ISO3 country code.
Returns:
list[int, float]: A list containing the latest available year and the calculated coefficient.
"""
```
this is called at parent function of `get_pop_coefficient` and will compare both result of world bank and UNSD to get latest one. currently UNSD is not supported.
Also, added some simple test cases by mocking world bank api.
> feat: added a function to compute population coefficient between target year and latest available year from world bank

- cbsurge/core.py
fixes #161
previously dir_path was set to `/app/cbsurge`, then walk_packages looked for folder name end with `cbsurge` and it has never found files for variables.
> fix: set dir_path to a parent folder of cbsurge package dir. so walk_packages can work

- cbsurge/admin/__init__.py
- cbsurge/admin/ocha.py
This branch:
1. [x] Adds `dst_path` and `layer_name` arguments to admin commands
2. [x] Closes #166
3. [x] Fixes issue with output admin geojson being invalid
> added dst_path and layer_name args to admin commands

- cbsurge/admin/__init__.py
In this PR:
1. [x] Added a check for if `fetch_admin` returns geojson and if not, to just log that it has not been found for the specified bounding box
Fixes #174
> fix: added check for geojson exists

- Dockerfile
I copy pyproject.toml and install dev/jupyter dependencies prior to `COPY . .`, so any source code changes won't cause installing the entire dependencies again.
> chore: install dev/jupyter dependencies before installing rapida package dependencies

- cbsurge/admin/__init__.py
In this PR:
1. [x] Renamed `save_geojson` function to `save`
2. [x] Made appropriate changes to the usage of the `save_geojson` to use `save`
> fix: rename `save_geojson` function to `save`

- .dockerignore
- .github/workflows/ci.yml
- Dockerfile
- Makefile
- README.md
previously, always installed package by `pip install -e .`. Now use `pip install .` to install package for production.
build for production locally is like the below command.
```shell
PRODUCTION=true make build
```
> fix: when PRODUCTION env is passed, install package without -e in Dockerfile for production.

- cbsurge/initialize.py
> fix: generate variables correctly by rapida init

- cbsurge/admin/__init__.py
in this PR:
1. [x] Removed `layer_name` from admin commands and set default to `admin{level}`
2. [x] manually remove file to avoid raising gdal errors where overwritting fails
3. [x] Changed `dst_path` argument to `destination_path` and made it used as an argument rather than option
Now complete admin command would be something like this:
`rapida admin ocha --bbox=33.681335,-0.131836,35.966492,1.158979 --admin_level=2 --clip data/admin2_ocha_cli.geojson`
Fixes #183
> feat: remove layer_name argument and implement code to manually remove outout file where it exists

- pyproject.toml
`mapclassify` is required to use choropleth map in leafmap
> fix: add mapclassify for leafmap

- Dockerfile
- cbsurge/az/blobstorage.py
- cbsurge/dataset2pmtiles.py
- pyproject.toml
closes #201
- there is a bug in upload_blob function, and I fixed it.
- added check_blob_exists function
- dataset2pmtiles was migrated from data-pipeline, and optimised the interface for rapida use case. Unnecessary features were deleted (such as uploading error file, ingesting layers as seperated files, etc).
> feat: migrated dataset2pmtiles from data-pipeline

- cbsurge/initialize.py
- cbsurge/session.py
fixes #226 
- allow users to continue doing initialization without azure authentication.
- call `setup_logger` to output logs properly
prompt is now like below if authentication failed.
- continue proceeding
```shell
rapida init
Welcome to rapida CLI tool!
Your setup has already been done. Would you like to do setup again? [y/N]: y
[02/20/25 05:57:26] WARNING  InteractiveBrowserCredential.get_token failed: Failed to open a browser                                                        interactive.py:228
WARNING  DefaultAzureCredential failed to retrieve a token from the included credentials.                                                   chained.py:152
Attempted credentials: …
```
> fix: add error handling properly to allow rapida init to conitnue initialization without authentication

- cbsurge/assess.py
- cbsurge/components/builtenv/electricity/__init__.py
- cbsurge/components/builtenv/electricity/variables.py
- cbsurge/core/variable.py
- cbsurge/initialize.py
the following variable definition is registered to config.json
```
"builtenv.electricity": {
"electricity_grid_length": {
"title": "Total length of electricity grid",
"source": "geohub:/api/datasets/310aadaa61ea23811e6ecd75905aaf29",
"operator": "sum"
}
}
```
electricity can be assessed like below command
```
rapida assess -c builtenv.electricity -v electricity_grid_length
```
> fix: electricity register variable

- pyproject.toml
xarray and localtileserver are needed for leafmap to use local tiff in the server
> fix: add xarray and localtileserver for jupyter to allow using local tiff for leafmap

- cbsurge/assess.py
- cbsurge/core/variable.py
these changes are necessary to develop other components since others have nested package structure unlike population.
The changes are brought from https://github.com/UNDP-Data/geo-cb-surge/pull/230
> fix: bring necessary changes from PR#230 first

- cbsurge/util/resolve_url.py
I created `resolve_url.py` under `util` package. Maybe in the future we can add another function in this file if we need to resolve URL for other provider datasets.
- Usage
```python
from cbsurge.util.resolve_url import resolve_geohub_url
data_url = "geohub:/api/datasets/019a4692967f6412fb70808ee325d0e3"
fgb_url = resolve_geohub_url(dataset_url=data_url, link_name="flatgeobuf")
logger.info(fgb_url)
```
> feat: add resolve_geohub_url function under util package

- cbsurge/components/rwi/__init__.py
- cbsurge/util/geo.py
fixes #246 
- moved `clip_raster_with_mask` to geo.py
- use gdal calc to compute mask area of variable raster source
- show rich progress during gdal calc computation
> fix: use gdal calc to mask raster. moved `clip_raster_with_mask` to geo.py

- cbsurge/components/buildings/__init__.py
- cbsurge/components/electricity/__init__.py
- cbsurge/components/population/__init__.py
- cbsurge/components/roads/__init__.py
- cbsurge/components/rwi/__init__.py
- cbsurge/core/variable.py
The __call__ methods was implemented one in the Variable superclass. However as @JinIgarashi pointed out it specific implementation details applicable to only population component (see force_compute) make it tricky to use this implementation in other components
As a result this PR removed the  implementation from core.variable into each component/variable type.
> move __call__/assess into every variable type from core

- cbsurge/assess.py
- cbsurge/util/download_geodata.py
closes #254
Now available components and variables are shown in help message
```shell
rapida assess --help
Usage: rapida assess [OPTIONS]
Assess the effect of natural or social hazard
Options:
-c, --components [buildings|rwi|electricity|population|roads|deprivation]
One or more components to be assessed. Valid
input example: -c buildings -c rwi
-v, --variables [nbuildings|buildings_area|rwi_mean|rwi_min|rwi_max|electricity_grid_length|electricity_grid_density|female_total|child_total|male_active|female_active|child_dependency|female_child|dependency|elderly_dependency|male_elderly|male_total|female_elderly|total|male_child|elderly_total|active_total|roads_count|roads_length|depriv_min|depriv_max|depriv_mean]
The variable/s to be assessed. Valid input
example: -v nbuildings -v …
```
> feat: dynamically set components and variables for click.option's choices

- cbsurge/components/buildings/variables.py
- cbsurge/components/deprivation/variables.py
- cbsurge/components/electricity/variables.py
- cbsurge/components/gdp/__init__.py
- cbsurge/components/gdp/variables.py
- cbsurge/components/population/variables.py
- cbsurge/components/roads/variables.py
- cbsurge/components/rwi/__init__.py
- cbsurge/components/rwi/variables.py
- cbsurge/initialize.py
- cbsurge/util/download_geodata.py
- fixes #63 
- compute sum/min/max/mean of GDP for each polygon of a project
- compute affected version of each variable if project mask is provided
- Use GDP data for target year if it is available.
- If GDP data is not available within forecasting data between 2020 and 2100, get the closest two years' data to interpolate target year's GDP data by using linear regression.
- fixes #276
added data license and attribution for each component variable setting. The latest config.json is like below
<details>
<summary>config.json</summary>
```json
{
"root_data_folder": "~/cbsurge",
"account_name": "undpgeohub",
"publish_container_name": "rapida",
"stac_container_name": "stacdata",
"file_share_name": "cbrapida",
"geohub_endpoint": "https://geohub.data.undp.org",
"variables": {
"population": { …
```
> feat: added GDP component, and added license/attribution for each component variable

- cbsurge/az/fileshare.py
- cbsurge/project/__init__.py
- cbsurge/project/project.py
- moved upload_project function to Project class
- added `-p` option to specify project folder, 
- or users can upload after moving to project folder
- check if project folder is valid for upload/publish command
> fix: improved CLI interface of rapida upload command

- cbsurge/project/__init__.py
fixed behaviour of downlaod command, added help documentation for the command.
```shell
rapida download --help
Usage: rapida download [OPTIONS] PROJECT_NAME DESTINATION_FOLDER
Download a project from Azure File Share
Usage:
First, please check available projects by using `rapida list` to find a
project name to download.
Then, download a project by using the below command:
rapida download <project name> <project folder path>
For example, if project name is `test`, you could run:
rapida download test ./data
OR
rapida download test ./data/test
The project data will be downloaded under ./data/test folder.
If a project data already exists in local, run the below command:
rapida download <project name> <project folder path> --overwrite
To use --overwrite, old project data in local storage will …
```
> fix: fixed download command behaviour and added more documentation

- cbsurge/az/fileshare.py
- cbsurge/cli.py
- cbsurge/project/__init__.py
- cbsurge/project/project.py
- cbsurge/session.py
- tests/cbsurge/test_session.py
- fixed a bug of upload command
- added delete command to delete a project from Azure File Share and local storage
```shell
rapida delete --help
Usage: rapida delete [OPTIONS]
Delete a project from local storage and Azure File Share if it was uploaded.
Usage:
If you are already in a project folder, run the below command:
rapida delete
If you are not in a project folder, run the below command:     rapida
delete --project=<project folder path>
This command shows prompts to confirm deletion of a project to prevent
deleting accidentally. If you wish to answer all prompts to yes, use -y
or --yes in the command:
rapida delete --yes
Options:
-p, --project DIRECTORY  Optional. A project folder with rapida.json can be
specified. If not, current directory is considered
as a project folder.
-y, …
```
> feat: implemented rapida delete command

- cbsurge/components/landuse/__init__.py
- cbsurge/components/landuse/stac.py
- pyproject.toml
This is first version of download function.
final output of download function will be like below folder structure
direct Tiff file under `data/landuse` is mosaic and masked by project area. 
sub folder like `MGRS-35MRT` is a folder for STAC item grid. When the function downloads jp2 data, it will reproject jp2 to ESRI:54009.
This function will firstly create VRT for each asset file like B02.vrt, B03.vrt. Then it will crop VRT by project area to create actual tiff file.
There are mixed resolution of 10m and 20m depending on asset. The download function will set highest resolution for all files. So, it will easily be consumed by model function.
```
./data/kigali_small/data
├── kigali_small.gpkg
├── landuse
│   ├── B02.tif
│   ├── B03.tif
│   ├── B04.tif
│   ├── B05.tif
│   ├── B06.tif
│   …
```
> fix: implemented download function for landuse component

- pyproject.toml
The docker image is too lartge (8.6 GB) and can no be deployed  with AZ web app. By removing the tensorflow from the dep it should be possible to deploy rapida server
> rm tensorflow to be able to deploy to web app

- .env.example
- cbsurge/initialize.py
- cbsurge/session.py
- docker-compose.yaml
- tests/cbsurge/test_session.py
fixes #320
new rapida init produces prompts like below
```shell
rapida init
Welcome to rapida CLI tool!
Your setup has already been done. Would you like to do setup again? [y/N]: y
[04/11/25 08:23:19] INFO     Token cached at /root/.cbsurge/zb5ZCVLrXSVDa8GXWV1lUmS_J.bin will expire in 3284.513695 secs                                                         surgeauth.py:260
Authentication successful.
Initialization was done. config file was saved to /root/.cbsurge/config.json
```
all internally used variables are exposed as environmental variables. those are indicated at `.env.example`
```
AZURE_STORAGE_ACCOUNT=
AZURE_PUBLISH_CONTAINER_NAME=
AZURE_STAC_CONTAINER_NAME=
AZURE_FILE_SHARE_NAME=
GEOHUB_ENDPOINT=
```
if environmental variables are missing, default value is used.
unused root data …
> fix: simplify `rapida init` command interface and message

- cbsurge/components/landuse/variables.py
fixes #330
new landuse component setting is like below
```json
"landuse": {
"built_area": {
"title": "Built-up area",
"source": "earth-search:sentinel-2-l1c:6",
"operator": "sum",
"percentage": true,
"license": "Proprietary",
"attribution": "ESA, Sinergise, AWS, Element 84, Brown, C.F., Brumby, S.P., Guzder-Williams, B. et al. (2022). Dynamic World, Near real-time global 10 m land use land cover mapping. Scientific Data, 9(1)."
},
"crops_area": {
"title": "Cropland area",
"source": "earth-search:sentinel-2-l1c:4",
"operator": "sum",
"percentage": true,
"license": "Proprietary",
"attribution": "ESA, Sinergise, AWS, Element 84, Brown, C.F., Brumby, S.P., Guzder-Williams, B. et al. (2022). Dynamic World, Near real-time global 10 m land use land cover mapping. Scientific Data, 9(1)."
}
},
```
> fix: added attibution and license for landuse component

- cbsurge/components/elegrid/__init__.py
- cbsurge/util/download_geodata.py
- cbsurge/util/read_bbox.py
closes #350 
The trouble with the download was a bug that showed whenever the number of workers/threads was larger or equal to number of polygons. Due to a logical but the download_vector function exited without collecting results from the threads and thus produced empty datasets
> fix download_vector bug

- cbsurge/cli/publish.py
- cbsurge/project/project.py
- cbsurge/util/dataset2pmtiles.py
fixes #355
- as default, all layers starting with `stats.` are converted to PMTiles
- added `-l/--layer` option to allow users to choose any layers to publish. In case, users want to include non-statistics layer like `polygon`, `mask`, `buildings`, etc, this option can be used to include any layers inside geopackage.
- If users pass invalid layer name, it shows error like below
```shell
rapida publish -l stats.ele
Usage: rapida publish [OPTIONS]
Try 'rapida publish -h' for help.
Error: Invalid value for '-l' / '--layer': Invalid layer: stats.ele. Valid options: polygons, mask, elegrid, elegrid.affected, stats.elegrid
```
- the latest help message for publish command is below
```shell
rapida publish -h
Usage: rapida publish [OPTIONS]
Publish project data to Azure and open GeoHub …
```
> feat: add -l/--layer option to choose layers to publish.

- pyproject.toml
> fix: add nest_asyncio to dependency in pyproject.toml

- pyproject.toml
fixes #372
In my local, by switching to tensorflow from tensorflow-cpu, it increases size for 6.38GB > 6.43GB. I think it is acceptable
> fix: switched tensorflow-cpu to tensorflow

- rapida/components/landuse/stac.py
this PR fixes bug of download task is not deleted if file already exists
> fix: remove download task if file already exists

- rapida/components/landuse/__init__.py
- rapida/components/landuse/constants.py
- rapida/components/landuse/stac.py
fixes #380 
- Store new metadata in geotif
- save `JP2_CONTENT_LENGTH` to tif file
- save `ITEM_DATETIME` to tif file
- save `CLOUD_COVER` to tif file
- Previously, only check if file already exists for skipping, now it checks if contentLength is same
- In STAC search function, check cloud cover rate and it use lower cloud image even it is older than others. I think lower cloud is more important for precise landuse prediction.
> fix: Store new metadata in geotif

- rapida/cli/assess.py
- rapida/components/landuse/__init__.py
- rapida/components/landuse/prediction.py
- rapida/components/landuse/stac.py
- tests/rapida/components/landuse/test_stac.py
Previously,
- it used fixed date range from 1 Jan to 31 Dec.
Now
- `--month` option is added for assess command
- end date is current year and month if `--year` and `--month` are not set. If `--year` and `--month` are set, they are used as end year month. If end year month is future, it uses current year and month for end date
- it searches 6 months duration ending at end year month.
- added test cases for `create_date_range` function.
- mask nodata value for harmonization from subtracting 1000 for the new data
- mask nodata pixels after prediction since the model will create pixels with value = 1 (tree) for no data pixels.
Assess command is now like below
```diff
rapida assess
Usage: rapida assess [OPTIONS]
Assess/evaluate a specific geospatial exposure components/variables
`-a/--all` …
```
> fix: improve search daterange, and handle nodata value for prediction and downloaded data correctly

- rapida/components/landuse/stac.py
sentinel 2 scene is 110x110km, so it tries to create voronoi polygons having 220km spacing within a merged polygon. If user gives a small area, it will search by a merged geometry.
original
Voronoi polygons
> fix: split target area into multiple voronoi polygons to search STAC item

- pyproject.toml
- rapida/components/landuse/prediction.py
closes #384
- added psutil to check the number of available CPUs
- run model concurrently. If 2 CPU is available, 2 workers will be running model.
- It shows progress task for each workers
just memo for my experiment
- current version
- tilesize: 256
- ProcessPoolExecutor: 432.8232669830322
- after applying changes of PR
- tilesize: 256
- ProcessPoolExecutor: 432.8232669830322 
- ThreadPoolExecutor: n/a
- tilesize: 512
- ProcessPoolExecutor: 236.56645345687866 seconds
- ThreadPoolExecutor: 295.22949504852295 seconds
- tilesize: 1024
- ProcessPoolExecutor: 172.0952889919281
- ThreadPoolExecutor: n/a
> fix: run prediction model concurrently with maximum workers from the number of CPU

- rapida/components/landuse/__init__.py
- rapida/components/landuse/stac.py
I updated download_from_https_async function logic of downloading a file
previously, it downloads file by 8192 chunk size, this becomes too many chunks and it takes a bit longer time to request HTTP everytime.
New approarch is to divide file to 10 chunks, and it downloads chunks with max 5 workers concurrently.
I tested in small area of Kigali
- before changing
```
[05/07/25 08:02:22] INFO     STAC Item search: 3.04833722114563 seconds                                                                                                    stac.py:613
[05/07/25 08:05:53] INFO     STAC Item download: 210.75929975509644 seconds                                                                                                stac.py:677
[05/07/25 08:05:55] INFO     Download completed: …
```
> fix: improve the performance of download 

- rapida/components/landuse/__init__.py
- rapida/components/landuse/constants.py
- rapida/components/landuse/sentinel_item.py
- rapida/components/landuse/stac.py
- created `SentinelItem` class to manage download and prediction per a STAC Item
- previously, it creates a VRT for each band, then run prediction for mosaic. Now prediction is done at each stac item level
- after download part is done, create a VRT for predicted land use image
- sort predicted image by datetime and cloud cover rate before creating mosaic (VRT)
> fix: restructure landuse component logic

- .github/workflows/ci.yml
- CONTRIBUTING.md
- Dockerfile
- Makefile
- README.md
- docker-compose.dev.yaml
- docker-compose.yaml
introducing multistage build to differentiate dev and prod image generation.
- Installation of rapida package is split into `dev` and `prod` stage
- if `--target=dev` is used to build, rapida is installed with `-e` which can be live updated from mounted code
- if `--target=prod` is used to build, rapida is installed without `-e` for production
- In Apple Silicon environment, some dependencies like `rasterio` and `exactextract` needs to be built from source code to generate whl. This compiling process failed because of lack of some package installation. I added `python3-dev` and `g++` to be installed in Dockerfile.
- Because of this above change, now arm64 docker image can be built for Mac environment. the performance of rapida in Mac becomes significantly faster.
- Added `CONTRIBUTING.md` …
> fix: introducing multistage build

- rapida/components/landuse/sentinel_item.py
- rapida/components/population/__init__.py
- rapida/util/download_remote_file.py
- create util functions to download remote file
- added `download_remote_file` for downloading a single file
- added `download_remote_files` for downloading a set of files concurrently
- Use new util function from sentinel_item.py to download asset files for land use
- Use new util function in population component instead of using Azure SDK
Due to switching from Azure SDK, now assess command should work without authentication.
I believe using asyncio.Semaphore to limit the maximum number of workers to fetch remote files can be a correct approarch. Also, compared to other approach of asyncio (for example, [download_raster](https://github.com/UNDP-Data/rapida/blob/29808c92d1834193958583799474acbdeb172479/rapida/util/download_geodata.py#L417-L421) function), Semaphore code can be much …
> fix: created util function to download remote files, and use it for both population and land use

- rapida/admin/osm.py
fixes #131
Previous code did clipping first, then get a centroid of polygon to fetch attributes. This leaded a weird behaviour if admin polygon has complicated shape after clipping.
Now, clipping has been moved to the end of function. It works properly with --clip option
> fix: do clip polygon at the end of fetch_admin code
