UNDP-Data/rapida

- README.md
- requirements.txt
fixes #75
also add some usage info in readme
> fix: add pycountry in dependency of requirements.txt.

- cbsurge/admin/osm.py
> fix: parse admin_level and osm_level variable into int if it is str type.

- Dockerfile
- README.md
- create_user.sh
- jupyterhub_config.py
folder structure in the container will be as follows:
- /data - it will be mounted to fileshare. All files under this folder will be kept
- /data/{username} - users can explore all users file, a user has no permission to edit other users' folder.
- /home/{username} - user home folder. This data will be lost when the server is restarted.
> fix: separate home and data folder in the container.

- Dockerfile
- Makefile
- docker-compose.yaml
I think it would be nice if vim can be used inside docker
> fix: add vim to docker

- pyproject.toml
want to use them in Jupyter Notebook
> feat: add folium and matplotlib to dependencies

- pyproject.toml
wanted to use ipywidgets in jupyter
> fix: add ipywidgets to pyproject.toml

- cbsurge/exposure/population/__init__.py
> fix: added description for population sync and aggregatre command

- cbsurge/exposure/population/constants.py
- cbsurge/exposure/population/worldpop.py
- aggregate total population
- it reuses downloaded tiff file instead of downloading it again for other variable
> feat: aggregate total population

- cbsurge/core.py
> fix: added path for walk_packages to only search modules under cbsurge folder.

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- Dockerfile
- README.md
- pyproject.toml
> chore: separate dependencies of testing and jupyter server from package itself

- cbsurge/admin/osm.py
- cbsurge/components/builtenv/buildings/fgb.py
- cbsurge/isobbox.py
- cbsurge/util.py
> improved robustness of httpx queries to overapss API

- cbsurge/assess.py
- cbsurge/components/population/__init__.py
- cbsurge/core.py
- cbsurge/util.py
This PR enbale rapida pop to assess polygons in multiple countries. It does so by preparing the variable over multiple countries (download, compute) and merging them into 1 VRT
> Feat/issue 182 multi-country mode

- cbsurge/admin/gui.py
This PR
1. [x] Adds GUI module so users don't get overwhelmed by code in jupyter notebooks
2. [x] Added controld for datasource selection, UNDP admin level selection, clip to bbox checkbox, save button, load button
> feat: add gui module

- cbsurge/admin/gui.py
In this PR:
1. [x] Changed default text of filechooser to be more descriptive
> fix: change filechooser text

- cbsurge/project/__init__.py
- cbsurge/project/project.py
> refactor: changed file structure for project.py

- cbsurge/project/project.py
> indent left save func in project init

- cbsurge/project/project.py
> set access_mode to append

- cbsurge/project/project.py
> add countries at all times

- cbsurge/util/download_geodata.py
- cbsurge/util/downloader.py
- cbsurge/util/read_bbox.py
1.  [x] Moved `download_geodata` to utils
2. [x] Added `return_fids` to assist in removing duplicated values that get duplicated due to them intersecting at admin boundaries
> refactor: move  function to utils

- cbsurge/util/download_geodata.py
- fix: added progress arg to the function to allow parent function to pass progress instance
- fix: stop the process of downloading when all downloading jobs finish to prevent going into infinite loop
> fix: added progress arg to the function to allow parent function to pass progress instance

- cbsurge/core/component.py
download function is no longer needed for component base class
> fix: deleted unused download function from component.py

- cbsurge/components/builtenv/__init__.py
deleted builtenv and natenv folders
> refactor: deleted builtenv and natenv folder since they are no longer needed

- cbsurge/components/roads/__init__.py
- cbsurge/util/download_geodata.py
I fixed roads component where using `download_vector` since https://github.com/UNDP-Data/geo-cb-surge/pull/252 introduced breaking changes, and road component has never worked properly.
after #252, `download_vector` is never come back if src_dataset_url does not start with `/vsicurl/`. so, I modified the function to add prefix if not there.
also, new `download_vector` function goes into infinite loop after downloading all chunks. So, I added `ndownloaded` variable to keep the number of records processed to escape infinite loop safely after finishing all chunks.
> fix: fixed bug of download_vector to go into infinite loop

- cbsurge/util/download_geodata.py
fixed to check the correct variable to exit infinite loop
> fix: check len(jobs) instead of len(futures)

- cbsurge/components/electricity/__init__.py
Refactored the Electricity component to use the download_vector function
> refactor: electricity to use `download_vector` func

- cbsurge/components/electricity/__init__.py
- cbsurge/project/project.py
incase of any duplicates in h3id, regenerate new ones for each unit to ensure that there are no duplicate h3ids
Fixes #261
> fix: use polyid in electricity

- cbsurge/components/roads/__init__.py
- cbsurge/components/rwi/__init__.py
so, components can work with -f
> fix: call download method from compute in rwi/roads

- cbsurge/components/gdp/__init__.py
- cbsurge/components/gdp/variables.py
- cbsurge/components/rwi/__init__.py
> fix: add percentage for gdp_sum variable

- cbsurge/components/rwi/__init__.py
there was a bug when no mask is provided for rwi component
> fix: fixed bug when no raster mask for rwi component

- cbsurge/components/electricity/__init__.py
- cbsurge/components/roads/__init__.py
> fix polyid for line variables (roads, elgrid)

- cbsurge/components/elegrid/__init__.py
- cbsurge/components/elegrid/variables.py
- cbsurge/initialize.py
Fixes tasks in issue #303 
1. [x] rename electricity component and its variables to elegrid (module, component, var_names )
2. [x] remove elegrid_count and roads_count variables
3. [x] implement affected version in download for elegrid like for roads
> refactor: #303

- cbsurge/components/landuse/__init__.py
- cbsurge/components/landuse/stac.py
In this PR
1. [x] modified the `download_stac` function to be async and download files in chunks of 5
> feat: parallel and async download of landuse data

- cbsurge/components/landuse/stac.py
this PR is going to set nodata value explicitly from stac item metadata for each asset.
mosaic by vrt looks ok in my local.
> fix: get nodata from stac item metadata instead of hardcoding

- cbsurge/components/landuse/prediction.py
- pyproject.toml
In this PR
1. [x] Removed unnused and unneccessary code in prediction and pyproject.toml
> fix: remove unused code

- cbsurge/components/buildings/__init__.py
- cbsurge/components/deprivation/__init__.py
to clean codes to delete unused imports and functions I discovered when I searched where geopandas are used
> refactor: deleted unused code and imports

- cbsurge/components/landuse/prediction.py
In this PR;
1. [x] Removed tensorflow import
> fix: remove tf import

- cbsurge/components/roads/__init__.py
- cbsurge/util/gpd_overlay.py
in this pr
1. [x] create `run_overlay` function to run overlay low memory for large datasets
> fix: use loops and parallel to run intersection overlay

- cbsurge/az/fileshare.py
- cbsurge/az/surgeauth.py
- cbsurge/cli/__init__.py
- cbsurge/cli/admin.py
- cbsurge/cli/assess.py
- cbsurge/cli/auth.py
- cbsurge/cli/create.py
- cbsurge/cli/delete.py
- cbsurge/cli/download.py
- cbsurge/cli/list.py
- cbsurge/cli/publish.py
- cbsurge/cli/upload.py
- cbsurge/components/buildings/__init__.py
- cbsurge/components/deprivation/__init__.py
- cbsurge/components/elegrid/__init__.py
- cbsurge/components/gdp/__init__.py
- cbsurge/components/landuse/__init__.py
- cbsurge/components/population/__init__.py
- cbsurge/components/roads/__init__.py
- cbsurge/components/rwi/__init__.py
- cbsurge/project/project.py
> feat: improve CLI interfaces

- cbsurge/az/blobstorage.py
- cbsurge/project/project.py
> fix: delete publishing blobs in delete command if exists

- cbsurge/project/project.py
> fix: check data is registered in geohub in delete command correctly

- cbsurge/az/authwidget.py
- cbsurge/az/surgeauth.py
> improve oauth url so it reports error like invalid scope

- cbsurge/az/authwidget.py
- cbsurge/util/geo.py
> force 2D geom coords on project import

- cbsurge/components/gdp/variables.py
- cbsurge/components/landuse/variables.py
- cbsurge/project/project.py
- cbsurge/util/dataset2pmtiles.py
fixes #331 
after executing `rapida publish` command, more description and attribution will be in PMTiles metadata.
GeoHub's data registration page will be like this.
> fix: more metadata to PMTiles from project settings

- cbsurge/cli/delete.py
- cbsurge/cli/init.py
- cbsurge/cli/upload.py
> feat: add `--no-input` to init and upload command

- cbsurge/cli/assess.py
- cbsurge/cli/init.py
- docker-compose.yaml
> explicit jupyter detection and console adjustment

- pyproject.toml
In this PR;
1. [x] Added tensorflow cpu
> feat: add tensorflow-cpu

- rapida/components/landuse/__init__.py
- rapida/components/landuse/prediction.py
fixes #374
- disable tensorflow logs
- use rich progress to show progress bar
> fix: optimise logging for landuse prediction

- rapida/components/landuse/stac.py
fixes #377
Before improving
- download 36 assets in Kigali: It took 784.9923686981201 seconds
After improving (always download with max 5 workers)
- download 36 assets in Kigali: it took 674.5051083564758 seconds
> fix: search stac items by polygons

- rapida/components/landuse/constants.py
- rapida/components/landuse/prediction.py
fixes #381 
fixes #382
it writes metadata like below
```shell
gdalinfo data/landuse/landuse_prediction.tif 
Driver: GTiff/GeoTIFF
Files: data/landuse/landuse_prediction.tif
Size is 1608, 1178
Coordinate System is:
PROJCRS["World_Cylindrical_Equal_Area",
BASEGEOGCRS["WGS 84",
DATUM["World Geodetic System 1984",
ELLIPSOID["WGS 84",6378137,298.257223563,
LENGTHUNIT["metre",1]],
ID["EPSG",6326]],
PRIMEM["Greenwich",0,
ANGLEUNIT["degree",0.0174532925199433,
ID["EPSG",9122]]]],
CONVERSION["Lambert Cylindrical Equal Area",
METHOD["Lambert Cylindrical Equal Area",
ID["EPSG",9835]],
PARAMETER["Latitude of 1st standard parallel",0,
ANGLEUNIT["degree",0.0174532925199433],
ID["EPSG",8823]],
PARAMETER["Longitude of natural origin",0,
ANGLEUNIT["degree",0.0174532925199433],
ID["EPSG",8802]], …
```
> feat: add landuse colormap and STATISTICS_UNIQUE_VALUES to tif

- rapida/session.py
In this PR:
1. [x] Get variable title name
> feat: get variable title name

- rapida/components/roads/__init__.py
- rapida/components/roads/variables.py
In this PR;
1. [x] Replaced `roads_count` variable with `roads_density`
> fix: replaced roads count with density

- rapida/admin/ocha.py
In this PR:
1. [x] I showed user readable error for layman user of rapida
> fix: show layman user readble error for ocha

- rapida/cli/assess.py
In this PR
1. Run a filter to filter out landuse command when processing all
Fixes #388
> fix: remove landuse when processing all

- rapida/cli/admin.py
1. [x] Improved help message from CGAZ
> fix: add help to cgaz

- rapida/admin/cgaz.py
In this PR
1. [x] Delete iso_3 field
> fix: remove duplicate iso_3 column

- README.md
I forgot to update texts in readme although I added flowchart...
> docs: added some explanation about cloud detect algorithm in landuse component

- rapida/az/surgeauth.py
> replace USER env var with getpass

- .github/workflows/ci.yml
- build docker images for both amd64 and arm64
- push multi platform images to container registry
> ci: upload multiplatform images

- rapida/project/project.py
> use os indep. line sep

- rapida/components/landuse/__init__.py
- rapida/components/landuse/download.py
- convert VRT to actual tiff file with band tag metadata
- so it will be easier to reuse final landuse file for a project
> fix: create a physical tiff file after creating mosaic vrt in landuse component

- .env.example
- .github/workflows/ci.yml
- README.md
fixes #428
@iferencik please check README.md whether my updates are appropriate.
> docs: updated documentation related to USER variable

- rapida/components/roads/__init__.py
- rapida/components/roads/variables.py
In this PR
1. [x] implemented new variables based on column values.
To do this, I added a filters to filter based on the column values and then only process those variables
> feat: implement new variables based on columns

- rapida/admin/cgaz.py
- rapida/cli/admin.py
> fix: issue with clipping when user doesn't specify - cgaz

- rapida/project/project.py
> feat: find probable match of columns with iso3

- pyproject.toml
- rapida/admin/cgaz.py
- rapida/components/buildings/__init__.py
- rapida/components/population/__init__.py
- rapida/components/population/pop_coefficient.py
- rapida/project/project.py
- rapida/util/countries.py
> fix: improve population of iso3 country code

- rapida/components/population/__init__.py
- rapida/core/variable.py
> fix: add kwargs to _compute_affected_ in population

- rapida/admin/cgaz.py
> feat: added  field to cgaz

- rapida/components/landuse/__init__.py
- rapida/components/landuse/download.py
- rapida/components/landuse/prediction/landuse.py
- rapida/components/landuse/sentinel_item.py
- rapida/components/landuse/stac_collection.py
- rapida/util/download_remote_file.py
In this PR.
1. [x] Simplified download
2. [x] Implemented smoother cancellation of download and prediction
3. [x] Cleanup and removal of unneeded code
> fix: download and cancellation

- rapida/components/population/__init__.py
In this PR
1. Fix bug of not awaiting coroutine `download_remote_files`
> fix: async function run of download_remote_files

- rapida/components/population/__init__.py
closes #478 
This PR changes the names of the column for pop variables to include target year
> add target year to pop stats layer attr table

- rapida/components/landuse/__init__.py
- rapida/components/landuse/download.py
- rapida/components/landuse/prediction/base.py
- rapida/components/landuse/sentinel_item.py
- rapida/components/landuse/stac_collection.py
- rapida/util/download_remote_file.py
> Refactor landuse

- rapida/components/landuse/__init__.py
In this PR
1. Re-enabe landuse evaluate and compute
> fix: re-enable landuse evaluate
